services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    user:
      postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./back/
      dockerfile: Dockerfile
    ports:
      - 5000:5000 # port forward local to docker container if we need to access. Can remove later.
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

volumes:
  db-data: